---
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - prettier
plugins:
  - prettier
  - react
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  node/no-unsupported-features/es-syntax: off
  node/no-unpublished-import: off
  react/prop-types: off
