steps:
  - name: "node:10.15.1"
    id: "Yarn Install"
    args: ["yarn", "install"]
    env:
      - NODE_ENV=development

  - name: "node:10.15.1"
    id: "Running unit tests"
    args: ["yarn", "test"]
    env:
      - NODE_ENV=development

  - name: "node:10.15.1"
    id: "Build Application with Webpack"
    args: ["yarn", "build"]
    env:
      - NODE_ENV=production

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Upload docker image to gcr.io"
    args: ["builds", "submit" ,"--project" ,"global-application-example" ,"--tag" ,"gcr.io/global-application-example/global-apps-frontend"]
    env:
      - NODE_ENV=production

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy Cloud Run Service"
    args: ["run", "deploy", "global-apps-frontend", "--project", "global-application-example", "--region", "europe-west1", "--allow-unauthenticated", "--image", "gcr.io/global-application-example/global-apps-frontend", "--platform", "managed"]
    env:
      - NODE_ENV=production
